#!/bin/sh

lll=$(tput bold)$(tput setaf 0); rrr=$(tput bold)$(tput setaf 1); ggg=$(tput bold)$(tput setaf 2); yyy=$(tput bold)$(tput setaf 3); bbb=$(tput bold)$(tput setaf 4); mmm=$(tput bold)$(tput setaf 5); ccc=$(tput bold)$(tput setaf 6); www=$(tput bold)$(tput setaf 7); xxx=$(tput bold)$(tput sgr0); uuu=$(tput cuu 2)

cmdrun () {
	echo "${yyy}----> ${ccc}$1 ${ggg}#-- ${bbb}$2${xxx}"; echo "$1" | sh
	echo "${bbb}<.... $1 #-- $2${xxx}"
}
cmdcont () {
	echo -e "${yyy}----> ${ccc}$1 ${ggg}#-- ${bbb}$2\n----> ${mmm}Enter ${ggg}to continue${xxx}:"
	read a ; echo "${uuu}"; echo "$1" | sh
	echo "${bbb}<.... $1 #-- $2${xxx}"
}
ALL_INSTALL="n"
cmdyes () {
	echo "${yyy}----> ${ccc}$1 ${ggg}#-- ${bbb}$2${xxx}"
	if [ "x${ALL_INSTALL}" = "xy" ]; then
		echo "$1" | sh ; echo "${bbb}<.... $1 #-- $2${xxx}"
	else
		echo "${yyy}----> ${rrr}press ${ccc}'${yyy}y${ccc}'${rrr} or Enter${xxx}:"; read a; echo "${uuu}"
		if [ "x$a" = "xy" ]; then
			echo "${rrr}-OK-${xxx}"; echo "$1" | sh
			echo "${bbb}<.... $1 press 'y' or Enter: #-- $2${xxx}"
		else
			echo "${rrr}[ ${bbb}$1 ${rrr}] ${mmm}<.... 명령을 실행하지 않습니다.${xxx}"
		fi
	fi
}
