#!/bin/sh

lll=$(tput bold)$(tput setaf 0); rrr=$(tput bold)$(tput setaf 1); ggg=$(tput bold)$(tput setaf 2); yyy=$(tput bold)$(tput setaf 3); bbb=$(tput bold)$(tput setaf 4); mmm=$(tput bold)$(tput setaf 5); ccc=$(tput bold)$(tput setaf 6); www=$(tput bold)$(tput setaf 7); xxx=$(tput bold)$(tput sgr0); uuu=$(tput cuu 2)
#-- echo "${lll}#--BLACK /// ${rrr}#--RED /// ${ggg}#--GREEN /// ${yyy}#--YELLOW /// ${bbb}#--BLUE /// ${mmm}#--MAGENTA /// ${ccc}#--CYAN /// ${www}#--WHITE /// ${xxx}#--XXX ///"

CMD_NAME=$(basename $0) # 명령줄에서 실행 프로그램 이름만 꺼냄
CMD_DIR=${0%/$CMD_NAME} # 실행 이름을 빼고 나머지 디렉토리만 담음
if [ "x$CMD_DIR" = "x" ] || [ "x$CMD_DIR" = "x$CMD_NAME" ]; then CMD_DIR="."; fi
cmdrun () {
        echo "${yyy}#-- ${ccc}$1 ${ggg}#-- ${bbb}$2${xxx}"; echo "$1" | bash
        echo "${bbb}#// $1 #-- $2${xxx}"
}
cmdend () {
        echo "${bbb}#--///-- ${mmm}$1${xxx}"
}
cmdcont () { #----> Enter to continue
	echo -e "${yyy}#-- ${ccc}$1 ${ggg}#-- ${bbb}$2\n----> ${mmm}Enter ${ggg}to continue${xxx}:"
	read a ; echo "${uuu}"; echo "$1" | bash; echo "${yyy}#-- ${bbb}$1 #-- $2${xxx}"
}
ALL_INSTALL="n"
cmdyes () { #-- press 'y' or Enter:
	echo "${yyy}#-- ${ccc}$1 ${ggg}#-- ${bbb}$2${xxx}"
	if [ "x${ALL_INSTALL}" = "xy" ]; then
		echo "$1" | bash; echo "${bbb}#// $1 #-- $2${xxx}"
	else
		echo "${yyy}#-- ${rrr}press ${ccc}'${yyy}y${ccc}'${rrr} or Enter${xxx}:"
		read a; echo "${uuu}"
		if [ "x$a" = "xy" ]; then
			echo "${rrr}-OK-${xxx}"; echo "$1" | bash
		else
			echo "${rrr}[ ${bbb}$1 ${rrr}] ${mmm}<.... 명령을 실행하지 않습니다.${xxx}"
		fi
	fi
}
cmdreada_s () { #-- "(1) INPUT: port no" "(서버 포트번호 입력시 숫자 표시 안됨)"
        echo "${yyy}#-- ${ccc}$1 ${ggg}#-- ${bbb}$2${xxx}"; read -s read_s
        if [ "x$read_s" = "x" ]; then exit -1; fi
}
wavbox=(NONE play-1-pbong.wav play-2-castanets.wav play-3-ddenng.wav play-4-tiiill.wav play-5-gguuuung.wav play-6-ddeeeng.wav)
wavhan=(ding_val=0:none =1:딩~ =2:캐스터네츠~ =3:뗑- =4:띠일~ =5:데에엥~~ =6:교회_뎅-)
bin_fs="${HOME}/bin/freesound"
ding_val=0 #-- =0:play 하지 않고 화면표시만 함, =1..6:이 스크립트에서 지정한 해당 값으로 play 함
dingding () { #-- dingding $ding_val #-- 작업완료시 알림밸 지정 용도.
        if [[ "x${ding_val}" < "x1" || "x${ding_val}" > "x6" ]]; then
                echo "${mmm}#-- play -q ${wavhan[$ding_val]}${xxx}"
        else
                play -q ${bin_fs}/${wavbox[$ding_val]} &
        fi
}
log_begin () { #-- 로그기록 시작
	logs_folder="${HOME}/zz00logs" ; if [ ! -d "${logs_folder}" ]; then cmdrun "mkdir ${logs_folder}" ; fi
	log_name="${logs_folder}/zz.$(date +"%y%m%d-%H%M%S")__RUNNING_${CMD_NAME}" ; touch ${log_name}
}
log_end {} { #-- 로그기록 끝
	rm -f ${log_name}; log_name="${logs_folder}/zz.$(date +"%y%m%d-%H%M%S")..${CMD_NAME}"
	touch ${log_name}; cmdrun "ls --color ${CMD_DIR}" ; ls --color ${logs_folder}
}
