#!/bin/sh

CMD_NAME=`basename $0` ; CMD_DIR=${0%/$CMD_NAME} ; if [ "x$CMD_DIR" == "x" ] || [ "x$CMD_DIR" == "x$CMD_NAME" ]; then CMD_DIR="." ; fi
cBlack=$(tput bold)$(tput setaf 0); cRed=$(tput bold)$(tput setaf 1); cGreen=$(tput bold)$(tput setaf 2); cYellow=$(tput bold)$(tput setaf 3); cBlue=$(tput bold)$(tput setaf 4); cMagenta=$(tput bold)$(tput setaf 5); cCyan=$(tput bold)$(tput setaf 6); cWhite=$(tput bold)$(tput setaf 7); cReset=$(tput bold)$(tput sgr0); cUp=$(tput cuu 2)

cmdRun () {
	echo "${cCyan}----> ${cYellow}$1 ${cGreen}#-- ${cCyan}$2${cReset}"; echo "$1" | sh
	echo "${cGreen}<---- ${cBlue}$1 ${cGreen}#-- $2${cReset}"
}
cmdCont () {
	echo -e "${cCyan}----> ${cYellow}$1 ${cGreen}#-- ${cCyan}$2\n----> ${cMagenta}Enter ${cGreen}to continue${cReset}:"
	read a ; echo "${cUp}"; echo "$1" | sh
	echo "${cGreen}<---- ${cBlue}$1 ${cGreen}#-- $2${cReset}"
}
allYn="n"
cmdYenter () {
	echo "${cCyan}----> ${cYellow}$1 ${cGreen}#-- ${cCyan}$2${cReset}"
	if [ "x${allYn}" = "xy" ]; then
		echo "$1" | sh ; echo "${cGreen}<---- ${cBlue}$1 ${cMagenta}#-- $2${cReset}"
	else
		echo "${cCyan}----> ${cRed}press ${cCyan}'${cYellow}y${cCyan}'${cRed} or Enter${cReset}:"; read a; echo "${cUp}"
		if [ "x$a" = "xy" ]; then
			echo "${cRed}-OK-${cReset}"; echo "$1" | sh
			echo "${cGreen}<---- ${cBlue}$1 press 'y' or Enter: ${cMagenta}#-- $2${cReset}"
		else
			echo "${cRed}[ ${cBlue}$1 ${cRed}] ${cMagenta}<--- 명령을 실행하지 않습니다.${cReset}"
		fi
	fi
}
eSq=0
eSqMsg=""
echoSeq () {
	if [ "x$1" = "x" ]; then
		echo "${cBlue}(${eSq}) ${eSqMsg}${cReset}" ; echo "${cBlue}#--${cReset}"
	else
		eSq=$(( ${eSq} + 1 ))
		echo "${cMagenta}(${eSq}) ${cCyan}$1${cReset}"
		eSqMsg=$1
	fi
}
cmdTTbegin () {
	echo "${cCyan}----> ${cRed}$1${cReset}"
}
cmdTTend () {
	echo "${cBlue}<---- ${cMagenta}$1${cReset}"
}
freesound_dir="${HOME}/bin/freesound"
ding_play () {
	if [ "x$PLAY_OK" = "xok" ]; then #-- play 설치가 된 경우,
		if [ "x$1" = "x1" ]; then play -q ${freesound_dir}/play-1-pbong.wav & #-- 91926__tim-kahn__ding.wav & #---- x1=딩~
		else if [ "x$1" = "x2" ]; then play -q ${freesound_dir}/play-2-castanets.wav & #-- 411459__inspectorj__castanets-multi-a-h1.wav & #---- x2=캐스터네츠~
		else if [ "x$1" = "x3" ]; then play -q ${freesound_dir}/play-3-ddenng.wav & #-- 339816__inspectorj__hand-bells-f-single.wav & #---- x3=뗅-
		else if [ "x$1" = "x4" ]; then play -q ${freesound_dir}/play-4-tiiill.wav & #-- 212541__misstickle__indian-bell-chime.wav & #---- x4=띠일~
		else if [ "x$1" = "x5" ]; then play -q ${freesound_dir}/play-5-gguuuung.wav & #-- 411090__inspectorj__wind-chime-gamelan-gong-a.wav & #---- x5=데에엥~~
		else play -q ${freesound_dir}/play-6-ddeeeng.wav & #-- 513865__wormletter__chime-c.wav & #---- x6=교회 뎅-
		fi ; fi ; fi ; fi ; fi
	else
		echo "${cRed}~~~ play-${1} ~~~${cReset}"
	fi
}
# ding_play 1 #-- 1=딩~ 2=캐스터네츠~ 3=뗅- 4=띠일~ 5=데에엥~~ 6=교회 뎅-
# $PLAY_OK="ok" #-- 인 경우만 사용할수 있다.

#-- source ${HOME}/bin/color_base #-- 230514일 1423 CMD_DIR CMD_NAME cmdRun cmdCont cmdYenter echoSeq cmdTTbegin cmdTTend ding_play
