#!/bin/sh

CMD_NAME=`basename $0` ; CMD_DIR=${0%/$CMD_NAME} ; if [ "x$CMD_DIR" == "x" ] || [ "x$CMD_DIR" == "x$CMD_NAME" ]; then CMD_DIR="." ; fi
cBlack=$(tput bold)$(tput setaf 0); cRed=$(tput bold)$(tput setaf 1); cGreen=$(tput bold)$(tput setaf 2); cYellow=$(tput bold)$(tput setaf 3); cBlue=$(tput bold)$(tput setaf 4); cMagenta=$(tput bold)$(tput setaf 5); cCyan=$(tput bold)$(tput setaf 6); cWhite=$(tput bold)$(tput setaf 7); cReset=$(tput bold)$(tput sgr0); cUp=$(tput cuu 2)

cmdRun () {
	echo "${cYellow}----> ${cCyan}$1 ${cGreen}#-- ${cBlue}$2${cReset}"; echo "$1" | sh
	echo "${cGreen}<---- ${cBlue}$1 ${cGreen}#-- ${cBlue}$2${cReset}"
}
cmdCont () {
	echo -e "${cYellow}----> ${cCyan}$1 ${cGreen}#-- ${cBlue}$2\n----> ${cMagenta}Enter ${cGreen}to continue${cReset}:"
	read a ; echo "${cUp}"; echo "$1" | sh
	echo "${cGreen}<---- ${cBlue}$1 ${cGreen}#-- ${cBlue}$2${cReset}"
}
ALL_INSTALL="n"
cmdYenter () {
	echo "${cYellow}----> ${cCyan}$1 ${cGreen}#-- ${cBlue}$2${cReset}"
	if [ "x${ALL_INSTALL}" = "xy" ]; then
		echo "$1" | sh ; echo "${cGreen}<---- ${cBlue}$1 ${cMagenta}#-- ${cBlue}$2${cReset}"
	else
		echo "${cYellow}----> ${cRed}press ${cCyan}'${cYellow}y${cCyan}'${cRed} or Enter${cReset}:"; read a; echo "${cUp}"
		if [ "x$a" = "xy" ]; then
			echo "${cRed}-OK-${cReset}"; echo "$1" | sh
			echo "${cGreen}<---- ${cBlue}$1 press 'y' or Enter: ${cMagenta}#-- ${cBlue}$2${cReset}"
		else
			echo "${cRed}[ ${cBlue}$1 ${cRed}] ${cMagenta}<--- 명령을 실행하지 않습니다.${cReset}"
		fi
	fi
}
eSq=0
eSqMsg=""
echoSeq () {
	if [ "x$1" = "x" ]; then
		echo "${cBlue}(${eSq}) ${eSqMsg}${cReset}" ; echo "${cBlue}#--${cReset}"
	else
		eSq=$(( ${eSq} + 1 ))
		echo "${cMagenta}(${eSq}) ${cCyan}$1${cReset}"
		eSqMsg=$1
	fi
}
cmdTTbegin () {
	echo "${cYellow}----> ${cRed}$1${cReset}"
}
cmdTTend () {
	echo "${cBlue}<---- ${cMagenta}$1${cReset}"
}

wavbox=(NONE play-1-pbong.wav play-2-castanets.wav play-3-ddenng.wav play-4-tiiill.wav play-5-gguuuung.wav play-6-ddeeeng.wav)
wavhan=(0=none 1=딩~ 2=캐스터네츠~ 3=뗑- 4=띠일~ 5=데에엥~~ 6=교회_뎅-)
bin_fs="${HOME}/bin/freesound"
#-- play -q ${bin_fs}/${wavbox[ 1 ]} & #-- 1=딩~
#-- play -q ${bin_fs}/${wavbox[ 2 ]} & #-- 2=캐스터네츠~
#-- play -q ${bin_fs}/${wavbox[ 3 ]} & #-- 3=뗑-
#-- play -q ${bin_fs}/${wavbox[ 4 ]} & #-- 4=띠일~
#-- play -q ${bin_fs}/${wavbox[ 5 ]} & #-- 5=데에엥~~
#-- play -q ${bin_fs}/${wavbox[ 6 ]} & #-- 6=교회_뎅-

# PLAY_OK="ok" #-- 인 경우만 사용할수 있다.
ding_play () {
	ding_val=$1
	if [[ "x${ding_val}" < "x1" || "x${ding_val}" > "x6" ]]; then ding_val="4" ; fi
	play -q ${bin_fs}/${wavbox[$ding_val]} &
	echo "${cRed}~~~ play-${1} ~~~${cReset}"
}

change_special_char () {
	#-- " str_01 " == 빈칸을 밑줄로.
	local str_01=$(echo ${original_file_name} | sed 's/ /_/g')
	#-- " str_02 " == 대문자를 소문자로.
	# https://varie.tistory.com/entry/Bash%EC%89%98%EC%97%90%EC%84%9C-%ED%8C%8C%EC%9D%BC%EB%AA%85-%EC%9D%BC%EA%B4%84-%EB%8C%80%EC%86%8C%EB%AC%B8%EC%9E%90-%EB%B3%80%ED%99%98
	local str_02=$(echo ${str_01,,})
	#-- 소문자를 대문자로 바꿀때는: str_02=$(echo ${str_01^^})
	#-- bash3.x 인 경우: str_02=$(echo ${str_01} | tr '[A-Z]' '[a-z]')
	#-- "str_03 " == 특수문자 삭제하거나 변경
	new_name=$(echo ${str_02} | sed 's/(/./g' | sed 's/)/./g' | sed 's/;/./g' | sed 's/</./g' | sed 's/>/./g' | sed 's/\[/./g' | sed 's/\]/./g' | sed 's/\//./g' | sed 's/+/./g' | sed 's/,/./g')
}

#-- source ${HOME}/bin/color_base #-- 230524수 0828 CMD_DIR CMD_NAME cmdRun cmdCont cmdYenter echoSeq cmdTTbegin cmdTTend ding_play change_special_char () <== original_file_name ==> new_name
