version: '3.8'
services:
  database:
    image: mysql:latest
    container_name: myxlsct
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    ports:
      - "7700:3306"
    volumes:
      - /home/docker/myxlsct:/var/lib/mysql
